/*
 * Post-it digitalization API
 * Post-it digitalization API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: muellerobin95@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.PostIt;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Detects Post-it notes and digitalizes their contents
     *
     * By passing in the appropriate options, you can digitalize the contents of Post-it notes 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexPostItsTest() throws ApiException {
        Object body = null;
        String pictureLink = null;
        List<PostIt> response = api.indexPostIts(body, pictureLink);

        // TODO: test validations
    }
}
