/*
 * Post-it digitalization API
 * Post-it digitalization API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: muellerobin95@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Coordinate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-17T10:09:37.599Z[GMT]")
public class Coordinate {
  @SerializedName("posX")
  private Double posX = null;

  @SerializedName("posY")
  private Double posY = null;

  public Coordinate posX(Double posX) {
    this.posX = posX;
    return this;
  }

   /**
   * Get posX
   * @return posX
  **/
  @Schema(example = "17.39", required = true, description = "")
  public Double getPosX() {
    return posX;
  }

  public void setPosX(Double posX) {
    this.posX = posX;
  }

  public Coordinate posY(Double posY) {
    this.posY = posY;
    return this;
  }

   /**
   * Get posY
   * @return posY
  **/
  @Schema(example = "83.91", required = true, description = "")
  public Double getPosY() {
    return posY;
  }

  public void setPosY(Double posY) {
    this.posY = posY;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Coordinate coordinate = (Coordinate) o;
    return Objects.equals(this.posX, coordinate.posX) &&
        Objects.equals(this.posY, coordinate.posY);
  }

  @Override
  public int hashCode() {
    return Objects.hash(posX, posY);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Coordinate {\n");
    
    sb.append("    posX: ").append(toIndentedString(posX)).append("\n");
    sb.append("    posY: ").append(toIndentedString(posY)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
