# coding: utf-8

"""
    Post-it digitalization API

    Post-it digitalization API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: muellerobin95@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.post_it import PostIt  # noqa: E501
from swagger_client.rest import ApiException


class TestPostIt(unittest.TestCase):
    """PostIt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostIt(self):
        """Test PostIt"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.post_it.PostIt()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
