/**
 * Post-it digitalization API
 * Post-it digitalization API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: muellerobin95@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Coordinate

/**
 * 
 * @param id 
 * @param contents 
 * @param color 
 * @param coordinates 
 * @param width 
 * @param height 
 */
data class PostIt (
    val id: java.util.UUID,
    val contents: kotlin.String,
    val color: kotlin.String,
    val coordinates: Coordinate,
    val width: kotlin.Double,
    val height: kotlin.Double

) {
}