/* 
 * Post-it digitalization API
 *
 * Post-it digitalization API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: muellerobin95@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Coordinate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CoordinateTests
    {
        // TODO uncomment below to declare an instance variable for Coordinate
        //private Coordinate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Coordinate
            //instance = new Coordinate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Coordinate
        /// </summary>
        [Test]
        public void CoordinateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Coordinate
            //Assert.IsInstanceOfType<Coordinate> (instance, "variable 'instance' is a Coordinate");
        }


        /// <summary>
        /// Test the property 'PosX'
        /// </summary>
        [Test]
        public void PosXTest()
        {
            // TODO unit test for the property 'PosX'
        }
        /// <summary>
        /// Test the property 'PosY'
        /// </summary>
        [Test]
        public void PosYTest()
        {
            // TODO unit test for the property 'PosY'
        }

    }

}
