# coding: utf-8

# flake8: noqa
"""
    Post-it digitalization API

    Post-it digitalization API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: muellerobin95@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.coordinate import Coordinate
from swagger_client.models.post_it import PostIt
