//
// Coordinate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Coordinate: Codable {

    public var posX: Double
    public var posY: Double

    public init(posX: Double, posY: Double) {
        self.posX = posX
        self.posY = posY
    }


}

