//
// PostIt.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostIt: Codable {

    public var _id: UUID
    public var contents: String
    public var color: String
    public var coordinates: Coordinate
    public var width: Double
    public var height: Double

    public init(_id: UUID, contents: String, color: String, coordinates: Coordinate, width: Double, height: Double) {
        self._id = _id
        self.contents = contents
        self.color = color
        self.coordinates = coordinates
        self.width = width
        self.height = height
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case contents
        case color
        case coordinates
        case width
        case height
    }

}

