# coding: utf-8

"""
    Post-it digitalization API

    Post-it digitalization API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: muellerobin95@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def index_post_its(self, body, picture_link, **kwargs):  # noqa: E501
        """Detects Post-it notes and digitalizes their contents  # noqa: E501

        By passing in the appropriate options, you can digitalize the contents of Post-it notes   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.index_post_its(body, picture_link, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object body: Picture containing the Post-it notes to digitalize. Only required if no query parameter is provided. (required)
        :param str picture_link: A link to the picture to be digitalized. Only required if no request body is provided. (required)
        :return: list[PostIt]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.index_post_its_with_http_info(body, picture_link, **kwargs)  # noqa: E501
        else:
            (data) = self.index_post_its_with_http_info(body, picture_link, **kwargs)  # noqa: E501
            return data

    def index_post_its_with_http_info(self, body, picture_link, **kwargs):  # noqa: E501
        """Detects Post-it notes and digitalizes their contents  # noqa: E501

        By passing in the appropriate options, you can digitalize the contents of Post-it notes   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.index_post_its_with_http_info(body, picture_link, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Object body: Picture containing the Post-it notes to digitalize. Only required if no query parameter is provided. (required)
        :param str picture_link: A link to the picture to be digitalized. Only required if no request body is provided. (required)
        :return: list[PostIt]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'picture_link']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method index_post_its" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `index_post_its`")  # noqa: E501
        # verify the required parameter 'picture_link' is set
        if ('picture_link' not in params or
                params['picture_link'] is None):
            raise ValueError("Missing the required parameter `picture_link` when calling `index_post_its`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'picture_link' in params:
            query_params.append(('pictureLink', params['picture_link']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['image/png'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/indexPostIts', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[PostIt]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
